import { StyleSheet, Platform } from 'react-native';
import { SIZES, FONTS, SHADOWS } from '../constants/theme';

const getStyles = (COLORS) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
        minHeight: Platform.OS === 'web' ? '100vh' : '100%',
    },
    aiActionRow: {
        flexDirection: 'row',
        paddingHorizontal: SIZES.padding,
        gap: 10,
        marginBottom: 24,
        marginTop: 10,
    },
    aiButton: {
        flex: 1,
        height: 110,
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        padding: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
    },
    aiButtonText: {
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.5,
        textAlign: 'center',
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    loadingText: {
        marginTop: 12,
        ...FONTS.h4,
        color: COLORS.primary,
    },
    aiResultContainer: {
        paddingVertical: 10,
    },
    aiResultBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.primary + '10',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 100,
        alignSelf: 'flex-start',
        marginBottom: 16,
        gap: 6,
    },
    aiResultBadgeText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: COLORS.primary,
    },
    aiFoodName: {
        ...FONTS.h2,
        color: COLORS.textHeading,
        marginBottom: 20,
    },
    aiStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
    },
    aiStatItem: {
        alignItems: 'center',
    },
    aiStatValue: {
        ...FONTS.h3,
        color: COLORS.textHeading,
        fontWeight: 'bold',
    },
    aiStatLabel: {
        ...FONTS.body5,
        color: COLORS.textSubtle,
        marginTop: 4,
    },
    aiDisclaimer: {
        ...FONTS.body5,
        color: COLORS.textInactive,
        textAlign: 'center',
        marginBottom: 24,
        fontStyle: 'italic',
    },
    contentWrapper: {
        flex: 1,
        minHeight: Platform.OS === 'web' ? '100vh' : '100%',
    },
    scrollContent: {
        flexGrow: 1,
        paddingTop: 10,
        paddingBottom: 80, // FAB ve alt boşluk için artırıldı
    },
    header: {
        paddingHorizontal: SIZES.padding,
        paddingTop: Platform.OS === 'ios' ? 50 : 20,
        paddingBottom: 20,
        backgroundColor: COLORS.background,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    logo: {
        width: 40,
        height: 40,
        borderRadius: 12,
    },
    headerTitleContainer: {
        justifyContent: 'center',
    },
    logoText: {
        fontSize: 22,
        fontWeight: '800',
        color: COLORS.textHeading,
        letterSpacing: -0.5,
        fontFamily: Platform.OS === 'ios' ? 'Inter-Bold' : 'sans-serif-medium',
    },
    username: {
        fontSize: 14,
        color: COLORS.textSubtle,
        fontWeight: '600',
        fontFamily: Platform.OS === 'ios' ? 'Inter-SemiBold' : 'sans-serif',
    },
    headerActions: {
        flexDirection: 'row',
        gap: 12,
    },
    actionButton: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: COLORS.surface,
        justifyContent: 'center',
        alignItems: 'center',
        ...SHADOWS.light,
    },
    userSection: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    welcomeText: {
        ...FONTS.body5,
        color: COLORS.textSubtle,
    },
    dateIntegratedNav: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.surfaceHighlight,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 6,
        marginBottom: 16,
        alignSelf: 'center',
        gap: 16,
    },
    dateText: {
        fontSize: 14,
        fontWeight: '700',
        color: COLORS.textHeading,
    },
    userName: {
        ...FONTS.h3,
        color: COLORS.textHeading,
    },
    headerActions: {
        flexDirection: 'row',
        gap: 12,
    },
    iconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.surfaceHighlight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    content: {
        flex: 1,
    },
    summaryCard: {
        marginTop: 10,
        marginHorizontal: SIZES.padding,
        marginBottom: 20,
        padding: 28,
        backgroundColor: COLORS.surface,
        borderRadius: 40,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        ...SHADOWS.dark,
    },
    summaryHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 20,
    },
    calorieInfo: {
        flex: 1,
    },
    remainingLabel: {
        ...FONTS.body4,
        color: COLORS.textSubtle,
    },
    remainingValue: {
        fontSize: 56,
        fontWeight: '900',
        color: COLORS.textHeading,
        letterSpacing: -2,
        lineHeight: 64,
    },
    kcalLabel: {
        ...FONTS.body3,
        color: COLORS.textSubtle,
        fontWeight: '600',
    },
    streakBadge: {
        backgroundColor: '#FF9F0A20',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#FF9F0A40',
    },
    streakText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FF9F0A',
    },
    progressContainer: {
        height: 12,
        backgroundColor: COLORS.surfaceHighlight,
        borderRadius: 6,
        marginBottom: 24,
        overflow: 'hidden',
    },
    progressBar: {
        height: '100%',
        backgroundColor: COLORS.primary,
        borderRadius: 6,
    },
    macrosRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        flexWrap: 'wrap', // Taşan içerikleri bir alt satıra veya esnek mesafeye alır
        gap: 12,
    },
    macroItem: {
        minWidth: '28%', // Makroların üst üste binmesini engellemek için minimum genişlik
    },
    macroHeader: {
        flexDirection: 'row',
        alignItems: 'baseline',
        gap: 4,
        marginBottom: 8,
    },
    macroLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: COLORS.textSubtle,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    macroValue: {
        fontSize: 16,
        fontWeight: '800',
        color: COLORS.textHeading,
        fontFamily: Platform.OS === 'ios' ? 'Inter-Bold' : 'sans-serif-medium',
    },
    macroBarBg: {
        height: 4,
        backgroundColor: COLORS.surfaceHighlight,
        borderRadius: 2,
        marginBottom: 6,
        overflow: 'hidden',
    },
    macroBarFill: {
        height: '100%',
        borderRadius: 2,
    },
    macroTarget: {
        fontSize: 10,
        color: COLORS.textInactive,
        fontWeight: '600',
    },
    coachCard: {
        marginHorizontal: SIZES.padding,
        marginBottom: SIZES.padding,
        padding: 20,
        backgroundColor: COLORS.surface,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: COLORS.border,
        ...SHADOWS.light,
    },
    coachHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 12,
    },
    coachAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    coachContent: {
        flex: 1,
    },
    coachTitle: {
        ...FONTS.body4,
        fontWeight: '700',
        color: COLORS.primary,
        marginBottom: 4,
    },
    coachText: {
        ...FONTS.body4,
        color: COLORS.textBody,
        lineHeight: 20,
        marginBottom: 16,
    },
    coachButtonsRow: {
        flexDirection: 'row',
        gap: 10,
    },
    coachActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: COLORS.primary + '10',
        borderWidth: 1,
        borderColor: COLORS.primary + '20',
    },
    coachActionButtonText: {
        fontSize: 12,
        fontWeight: '700',
        color: COLORS.primary,
    },
    section: {
        paddingHorizontal: SIZES.padding,
        marginBottom: 30,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 16,
    },
    sectionTitle: {
        ...FONTS.h3,
        color: COLORS.textHeading,
    },
    mealCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.surface,
        borderRadius: 24,
        padding: 16,
        marginBottom: 8, // Genişletilebilir liste için boşluğu azalttım
        borderLeftWidth: 4,
        ...SHADOWS.light,
    },
    iconContainer: {
        width: 52,
        height: 52,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    mealInfo: {
        flex: 1,
        marginLeft: 16,
    },
    mealName: {
        ...FONTS.h4,
        color: COLORS.textHeading,
        marginBottom: 2,
    },
    listContainer: {
        paddingBottom: Platform.OS === 'web' ? 100 : 120, // FAB ve tab bar iÃ§in boÅŸluk
    },
    mealCaloriesActive: {
        ...FONTS.body4,
        fontWeight: '700',
    },
    mealCaloriesEmpty: {
        ...FONTS.body5,
        color: COLORS.textInactive,
    },
    mealActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    addButton: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: COLORS.surfaceHighlight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    waterCard: {
        backgroundColor: COLORS.surface,
        borderRadius: 32,
        padding: 24,
        marginHorizontal: SIZES.padding,
        marginBottom: SIZES.padding,
        ...SHADOWS.medium,
    },
    waterHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 20,
    },
    waterTitle: {
        ...FONTS.h4,
        color: COLORS.textHeading,
        marginBottom: 4,
    },
    waterValue: {
        fontSize: 18,
        fontWeight: '800',
        color: COLORS.water,
    },
    waterTarget: {
        fontSize: 12,
        color: COLORS.textSubtle,
        fontWeight: '400',
    },
    waterScroll: {
        marginBottom: 24,
    },
    waterGrid: {
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 4, // Kaydırma sırasında ilk/son bardağın kenara yapışmaması için
    },
    waterGlass: {
        width: 60, // Sabit genişlik, kaydırma sırasında stabilite sağlar
        height: 80, // Biraz daha uzun, altına ml yazısı gelecek
        paddingVertical: 10,
        borderRadius: 16,
        backgroundColor: COLORS.surfaceHighlight,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.03)',
    },
    waterGlassActive: {
        backgroundColor: COLORS.water + '15',
        borderColor: COLORS.water + '40',
    },
    waterControls: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 16,
    },
    waterButton: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: COLORS.surfaceHighlight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    waterButtonAdd: {
        backgroundColor: COLORS.water,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.6)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: COLORS.surface,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        height: '85%',
        padding: SIZES.padding,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        paddingHorizontal: 4,
    },
    modalTitle: {
        ...FONTS.h2,
        color: COLORS.textHeading,
    },
    searchContainer: {
        flexDirection: 'row',
        backgroundColor: COLORS.surfaceHighlight,
        borderRadius: 16,
        paddingHorizontal: 16,
        alignItems: 'center',
        height: 56,
        marginBottom: 24,
    },
    searchInput: {
        flex: 1,
        marginLeft: 12,
        ...FONTS.body3,
        color: COLORS.textHeading,
    },
    resultCard: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    resultInfo: {
        flex: 1,
    },
    resultName: {
        ...FONTS.body3,
        fontWeight: '600',
        color: COLORS.textHeading,
    },
    resultBrand: {
        ...FONTS.body5,
        color: COLORS.textSubtle,
        marginTop: 2,
    },
    resultNutrients: {
        alignItems: 'flex-end',
    },
    resultCalories: {
        ...FONTS.body4,
        fontWeight: '700',
        color: COLORS.primary,
    },
    resultUnit: {
        ...FONTS.body5,
        color: COLORS.textInactive,
    },
    gramStepContent: {
        flex: 1,
        alignItems: 'center',
        paddingTop: 20,
    },
    foodLabel: {
        ...FONTS.h3,
        color: COLORS.textHeading,
        marginBottom: 8,
    },
    brandLabel: {
        ...FONTS.body4,
        color: COLORS.textSubtle,
        marginBottom: 40,
    },
    gramInputContainer: {
        alignItems: 'center',
        marginBottom: 40,
    },
    gramInput: {
        fontSize: 64,
        fontWeight: '800',
        color: COLORS.primary,
        textAlign: 'center',
    },
    gramUnit: {
        ...FONTS.h3,
        color: COLORS.textSubtle,
        marginTop: -8,
    },
    macroPreview: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 'auto',
    },
    confirmBtn: {
        backgroundColor: COLORS.primary,
        width: '100%',
        height: 64,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        ...SHADOWS.medium,
    },
    confirmBtnText: {
        ...FONTS.h3,
        color: '#FFF',
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyText: {
        ...FONTS.body3,
        color: COLORS.textInactive,
        marginTop: 12,
    },
    waterInput: {
        fontSize: 48,
        fontWeight: '800',
        color: COLORS.water,
        textAlign: 'center',
        marginBottom: 24,
    },
    fabContainer: {
        position: 'absolute',
        bottom: 40,
        right: SIZES.padding,
        alignItems: 'center',
    },
    fab: {
        position: 'absolute',
        bottom: 30,
        right: SIZES.padding,
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        ...SHADOWS.dark,
        zIndex: 10,
    },
    fabOptions: {
        position: 'absolute',
        bottom: 80, // FAB'n hemen stnde
        right: 0,
        alignItems: 'flex-end',
        gap: 12,
        paddingBottom: 12,
    },
    fabOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    fabOptionLabel: {
        backgroundColor: COLORS.surface,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        ...SHADOWS.light,
        color: COLORS.textHeading,
        fontSize: 14,
        fontWeight: '600',
    },
    fabOptionBtn: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: COLORS.surface,
        justifyContent: 'center',
        alignItems: 'center',
        ...SHADOWS.medium,
    },
    aiModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        padding: 20,
    },
    aiCard: {
        backgroundColor: COLORS.surface,
        borderRadius: 30,
        padding: 24,
        ...SHADOWS.dark,
    },
    aiHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 20,
    },
    aiTitle: {
        ...FONTS.h3,
        color: COLORS.primary,
    },
    aiInput: {
        ...FONTS.body3,
        color: COLORS.textHeading,
        height: 120,
        textAlignVertical: 'top',
        backgroundColor: COLORS.surfaceHighlight,
        borderRadius: 20,
        padding: 16,
        marginBottom: 20,
    },
    aiButtonRow: {
        flexDirection: 'row',
        gap: 12,
    },
    aiCancelBtn: {
        flex: 1,
        padding: 16,
        borderRadius: 16,
        alignItems: 'center',
        backgroundColor: COLORS.surfaceHighlight,
    },
    aiSubmitBtn: {
        flex: 2,
        padding: 16,
        borderRadius: 16,
        alignItems: 'center',
        backgroundColor: COLORS.primary,
    },
    aiBtnText: {
        fontWeight: 'bold',
        color: COLORS.textHeading,
    },
    aiSubmitText: {
        fontWeight: 'bold',
        color: '#fff',
    },
    recordingOverlay: {
        flex: 1,
        backgroundColor: 'rgba(16, 185, 129, 0.95)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    micContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
    },
    recordingText: {
        color: '#fff',
        ...FONTS.h3,
        marginBottom: 8,
    },
    recordingSubtext: {
        color: 'rgba(255,255,255,0.8)',
        ...FONTS.body4,
        marginBottom: 60,
    },
    stopButton: {
        paddingHorizontal: 32,
        paddingVertical: 16,
        borderRadius: 100,
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    stopButtonText: {
        color: '#fff',
        ...FONTS.h4,
        fontWeight: 'bold',
    },
    trendsOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    trendsContent: {
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 20,
        height: '85%',
        backgroundColor: COLORS.background,
    },
    trendsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    trendsTitle: {
        fontSize: 22,
        fontFamily: FONTS.bold,
        color: COLORS.textHeading,
    },
    trendsLoading: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    chartContainer: {
        flexDirection: 'row',
        height: 200,
        marginBottom: 30,
        backgroundColor: COLORS.surfaceHighlight,
        borderRadius: 20,
        padding: 15,
    },
    chartYAxis: {
        justifyContent: 'space-between',
        paddingRight: 10,
        paddingBottom: 25,
    },
    yAxisLabel: {
        fontSize: 10,
        color: COLORS.textSubtle,
        fontFamily: FONTS.medium,
    },
    barsArea: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        position: 'relative',
    },
    barColumn: {
        alignItems: 'center',
        flex: 1,
    },
    bar: {
        width: 14,
        borderRadius: 7,
        marginBottom: 8,
    },
    barLabel: {
        fontSize: 10,
        color: COLORS.textSubtle,
        fontFamily: FONTS.medium,
    },
    targetLine: {
        position: 'absolute',
        left: 0,
        right: 0,
        height: 1,
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.1)',
        zIndex: -1,
    },
    weeklyInsightCard: {
        backgroundColor: COLORS.primary + '08',
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
    },
    weeklyInsightHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 10,
    },
    weeklyInsightTitle: {
        fontSize: 16,
        fontFamily: FONTS.bold,
        color: COLORS.textHeading,
    },
    weeklyInsightText: {
        fontSize: 14,
        fontFamily: FONTS.medium,
        color: COLORS.textBody,
        lineHeight: 22,
    },
    waterStatsCard: {
        padding: 20,
        backgroundColor: COLORS.white,
        borderRadius: 20,
        marginBottom: 30,
    },
    cardSmallTitle: {
        fontSize: 15,
        fontFamily: FONTS.bold,
        color: COLORS.textHeading,
        marginBottom: 15,
    },
    waterDotGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    waterDotContainerBase: {
        alignItems: 'center',
    },
    waterDotBase: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginBottom: 6,
    },
    dotLabelBase: {
        fontSize: 10,
        color: COLORS.textSubtle,
    },
    expandedFoodList: {
        backgroundColor: COLORS.surface + '80',
        marginHorizontal: SIZES.padding / 2,
        borderBottomLeftRadius: SIZES.radius,
        borderBottomRightRadius: SIZES.radius,
        padding: SIZES.base,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
        marginTop: -SIZES.base,
        zIndex: -1,
    },
    foodItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.05)',
    },
    foodItemInfo: {
        flex: 1,
        marginRight: 10,
    },
    foodItemName: {
        fontSize: 14,
        color: COLORS.textHeading,
        fontWeight: '500',
    },
    foodItemCal: {
        fontSize: 12,
        color: COLORS.textSubtle,
        marginTop: 2,
    },
    deleteButton: {
        padding: 8,
    },
    tabContainer: {
        flexDirection: 'row',
        marginBottom: SIZES.base * 2,
        backgroundColor: COLORS.surfaceHighlight,
        borderRadius: SIZES.radius / 2,
        padding: 4,
    },
    tab: {
        flex: 1,
        paddingVertical: 8,
        alignItems: 'center',
        borderRadius: SIZES.radius / 2 - 2,
    },
    activeTab: {
        backgroundColor: COLORS.surface,
        ...SHADOWS.light,
    },
    tabText: {
        fontSize: 13,
        fontWeight: '600',
        color: COLORS.textInactive,
    },
    activeTabText: {
        color: COLORS.primary,
    },
    suggestionBody: {
        paddingHorizontal: 5,
        paddingBottom: 10,
    },
    suggestionLoading: {
        alignItems: 'center',
        paddingVertical: 30,
    },
    suggestionLoadingText: {
        marginTop: 15,
        color: COLORS.textSubtle,
        fontSize: 14,
    },
    suggestionCard: {
        backgroundColor: COLORS.primary + '10',
        borderRadius: SIZES.radius,
        padding: 15,
        borderWidth: 1,
        borderColor: COLORS.primary + '20',
        marginBottom: 10,
    },
    suggestionText: {
        fontSize: 15,
        color: COLORS.textHeading,
        lineHeight: 22,
        textAlign: 'left',
        fontStyle: 'italic',
    },
    suggestionAction: {
        backgroundColor: COLORS.primary,
        paddingVertical: 14,
        borderRadius: SIZES.radius,
        alignItems: 'center',
    },
    suggestionActionText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    resultRightSide: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    favIconBtn: {
        padding: 4,
    },
    barcodeModalContainer: {
        flex: 1,
        backgroundColor: '#000',
    },
    scanner: {
        flex: 1,
    },
    scannerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    unfocusedContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        width: '100%',
    },
    focusedRow: {
        flexDirection: 'row',
        height: 200,
    },
    focusedContainer: {
        width: 280,
        height: 200,
        borderWidth: 2,
        borderColor: '#fff',
        backgroundColor: 'transparent',
        borderRadius: 16,
    },
    closeScannerButton: {
        position: 'absolute',
        top: 40,
        right: 20,
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    scannerInfo: {
        position: 'absolute',
        bottom: 80,
        left: 0,
        right: 0,
        alignItems: 'center',
    },
    scannerInfoText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
    },
    // Missing weekly trends styles
    chartYAxis: {
        justifyContent: 'space-between',
        paddingRight: 10,
        paddingBottom: 25,
    },
    yAxisLabel: {
        fontSize: 10,
        color: COLORS.textSubtle,
        fontFamily: FONTS.medium,
    },
    barsArea: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        position: 'relative',
    },
    barColumn: {
        alignItems: 'center',
        flex: 1,
    },
    bar: {
        width: 14,
        borderRadius: 7,
        marginBottom: 8,
    },
    barLabel: {
        fontSize: 10,
        color: COLORS.textSubtle,
        fontFamily: FONTS.medium,
    },
    targetLine: {
        position: 'absolute',
        left: 0,
        right: 0,
        height: 1,
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.1)',
        zIndex: -1,
    },
    insightCard: {
        marginHorizontal: SIZES.padding,
        marginBottom: SIZES.padding,
        padding: 24,
        backgroundColor: COLORS.surface,
        borderRadius: 24,
        borderLeftWidth: 4,
        alignItems: 'center', // Ortalama iÃ§in eklendi
        ...SHADOWS.light,
    },
    insightHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center', // Ortalama iÃ§in eklendi
        gap: 8,
        marginBottom: 12,
    },
    insightTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.textHeading,
    },
    insightMessage: { // insightText yerine insightMessage kullanÄ±ldÄ±
        fontSize: 14,
        color: COLORS.textBody,
        lineHeight: 22,
        textAlign: 'center', // Ortalama iÃ§in eklendi
    },
    waterGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    waterDotContainer: {
        alignItems: 'center',
    },
    waterDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginBottom: 6,
    },
    dotLabel: {
        fontSize: 10,
        color: COLORS.textSubtle,
    },
    modalSubtitle: {
        ...FONTS.body4,
        color: COLORS.textSubtle,
        lineHeight: 20,
    },
    confirmButton: {
        backgroundColor: COLORS.primary,
        width: '100%',
        height: 56,
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        ...SHADOWS.medium,
    },
    confirmButtonText: {
        ...FONTS.h4,
        color: '#FFF',
        fontWeight: 'bold',
    },
    recipeCard: {
        marginTop: 10,
    },
    recipeTitle: {
        ...FONTS.h3,
        color: COLORS.textHeading,
    },
    galleryScanButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.12)',
        paddingHorizontal: 20,
        paddingVertical: 14,
        borderRadius: 20,
        marginTop: 24,
        gap: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.15)',
    },
    galleryScanButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.3,
    },
});

export default getStyles;
